version: "1.1"
stages:
  - stage:
      - api-test:
          alias: api-test
          version: "2.0"
          params:
            asserts:
              - arg: a
                value: "200"
            body:
              type: none
            method: GET
            out_params:
              - expression: status
                key: a
                source: status
            url: www.jflejfl.com
          loop:
            break: task_status == 'Success'
            strategy:
              max_times: 3
              decline_ratio: 3
              decline_limit_sec: 3
              interval_sec: 2
